### ISSUE TITLE
Implement four of the functions to operate on 3D data (time,latitude,longitude) and return 2D arrays

### ISSUE THREAD

**Issue by bascrezee** [bascrezee/trend_framework#14]
- [x] Theil-Sen function, returning
  - [x] slope
- [x] MK test function, returning
  - [x] test outcome (negative trend, no trend, positive trend)
- [x] linear trend, returning
  - [x] slope
  - [x] pvalue
- [x] Weatherhead

**Comment by bascrezee** [comment]
Does the operation need to be parallelized?

Some outcome of the %timeit functions operating on yearly mean data over a timespan of 67 years:

Example dataset resolution: 0.25 deg = 4*180*360 = 259200 grid cells

| Function  | Time per grid cell (ms) | Time per dataset (s) |
| ------------- | ------------- | ------------- |
| Theil-Sen  | 0.9 | 233 |
| MK test | 3.5 | 900 |
| Linear | 0.75 | 194 |
| Weatherhead | 68 | 17625 |

**Comment by BenMGeo** [comment]
Weatherhead would still stay below 5 minutes. I think this should be fine.

**Comment by BenMGeo** [comment]
Question: 
Do we go for strict temporal implementation? or do we also implement trends with height?

**Comment by bascrezee** [comment]
> Weatherhead would still stay below 5 minutes. I think this should be fine.

Unfortunately not, the last column is in seconds... --> so it would stay below 5 hours :/ the other operations are all fine and would finish in a few minutes. We can look into it at a later stage. Today I hope to push Theil-Sen / MK test and Linear.

>  Do we go for strict temporal implementation? or do we also implement trends with height?
I would say for now we go for strict temporal implementation, we have to prioritize.

**Comment by bascrezee** [comment]
I just updated the checklist, current functionality is shown here: 
https://github.com/bascrezee/trend_framework/blob/dev/example_trends_3d.ipynb

**Comment by bascrezee** [comment]
All functionality has been implemented
