### ISSUE TITLE
Implement correct behaviour of trend tests on datasets with gaps

### ISSUE THREAD

**Issue by bascrezee** [bascrezee/trend_framework#36]
Suggested approach

- The trend functions always return a value when there are at least two valid points along the time axis

- Make the user aware of this and stress the importance of a proper gap handling before running the trend diagnostics

Current status of functions that can handle gaps:

- [x] linear_trend
- [x] theilsen_trend
- [x] mannkendall

The below functions return nan when there are one or more gaps along the time axis for a certain gridpoint
- detrend
- weatherhead

**Comment by hirschim** [comment]
possibly an option for the nan-behavior, could be common for all four functions

**Comment by bascrezee** [comment]
From an implementation perspective it is much more straight forward to not implement a check on NaN when calling the trend functions, but always ensure that a valid float is returned unless no trend can be calculated (i.e. when there are less than 2 valid points along the time axis). 

Of course, this needs to be clearly documented and the users should be aware of this behaviour.

**Comment by BenMGeo** [comment]
sounds good... np.nan should only be returned if a reasonable part is missing. We could also think of cutting the data down to the maximum non nan extent (otherwise we have something like extrapolating?) and a threshold what minimal percentage should be available to calculate trends.

First thing is really leading to a map of first date of data and last date of data per pixel. which might also come in handy.

**Comment by bascrezee** [comment]
Thanks for your comments :) 

> sounds good... np.nan should only be returned if a reasonable part is missing. 

Yes, my suggestion is to always return a value if it can be calculated (i.e. minimum two valid points), the ECV evaluator should make use of the seperate helper function on frac to mask the data. 

> We could also think of cutting the data down to the maximum non nan extent (otherwise we have something like extrapolating?) and a threshold what minimal percentage should be available to calculate trends.

I see your point, but I think it is up to the evaluator to check that the trend test is executed over a period with a sufficiently high amount of valid data. The usual Xarray functionality and the valid fraction helper function give her/him the tools to easily do so.


> 
> First thing is really leading to a map of first date of data and last date of data per pixel. which might also come in handy.

Yes, I agree that that would be a handy function, but not part of the core trend functions. A nice-to-have I would say.
